
-- Drop existing tables if they exist to ensure a clean slate.
DROP TABLE IF EXISTS "public"."services";

CREATE TABLE "public"."services" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "slug" "text" NOT NULL,
    "title" "text" NOT NULL,
    "image" "text",
    "short_description" "text",
    "long_description" "text",
    "content_sections" "jsonb",
    "icon_svg" "text",
    "show_benefits" boolean DEFAULT false NOT NULL,
    "benefits" "jsonb",
    "show_target_audience" boolean DEFAULT false NOT NULL,
    "target_audience" "text",
    "show_plans" boolean DEFAULT false NOT NULL,
    "plans" "jsonb",
    "show_steps" boolean DEFAULT false NOT NULL,
    "steps" "jsonb",
    "show_faqs" boolean DEFAULT false NOT NULL,
    "faqs" "jsonb",
    "show_related_services" boolean DEFAULT false NOT NULL,
    "related_services" _text
);

-- Set up the sequence and primary key for the services table
ALTER TABLE "public"."services" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."services_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY "public"."services" ADD CONSTRAINT "services_pkey" PRIMARY KEY ("id");

-- Initial data for the services
INSERT INTO "public"."services" (slug, title, image, short_description, show_related_services, related_services) VALUES
('life-insurance', 'Life Insurance', 'https://placehold.co/600x400.png', 'Secure your family''s future with our comprehensive life insurance plans.', true, '{"visitor-insurance", "super-visa-insurance", "health-dental"}'),
('visitor-insurance', 'Visitor Insurance', 'https://placehold.co/600x400.png', 'Emergency medical coverage for visitors to Canada.', true, '{"life-insurance", "super-visa-insurance", "travel-insurance-canadians"}'),
('super-visa-insurance', 'Supervisa Insurance', 'https://placehold.co/600x400.png', 'Mandatory medical insurance for parents and grandparents visiting Canada on a Super Visa.', true, '{"life-insurance", "visitor-insurance", "travel-insurance-canadians"}'),
('resp', 'RESP (Registered Education Savings Plan)', 'https://placehold.co/600x400.png', 'Save for your child''s post-secondary education with tax-sheltered investment growth.', true, '{"tfsa", "rrsp", "life-insurance"}'),
('tfsa', 'TFSA (Tax-Free Savings Account)', 'https://placehold.co/600x400.png', 'Grow your savings tax-free for any goal you have.', true, '{"resp", "rrsp", "life-insurance"}'),
('rrsp', 'RRSP (Registered Retirement Savings Plan)', 'https://placehold.co/600x400.png', 'Save for your retirement with tax-deductible contributions.', true, '{"tfsa", "resp", "life-insurance"}'),
('health-dental', 'Extended Health and Dental Plan', 'https://placehold.co/600x400.png', 'Cover medical expenses not included in your provincial plan.', true, '{"life-insurance", "visitor-insurance", "super-visa-insurance"}'),
('travel-insurance-canadians', 'Travel Insurance for Canadians', 'https://placehold.co/600x400.png', 'Travel with peace of mind knowing you''re covered for medical emergencies abroad.', true, '{"visitor-insurance", "super-visa-insurance", "life-insurance"}'),
('international-students-plan', 'International Students Plan', 'https://placehold.co/600x400.png', 'Affordable health insurance for international students studying in Canada.', true, '{"visitor-insurance", "health-dental", "travel-insurance-canadians"}');

-- Set up Row Level Security
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON "public"."services" FOR SELECT USING (true);
CREATE POLICY "Enable all for service role" ON "public"."services" TO service_role USING (true) WITH CHECK (true);
