
-- Drop the old table if it exists
DROP TABLE IF EXISTS public.quote_submissions;

-- Create the new, detailed table
CREATE TABLE public.quote_submissions (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,

    -- Step 1: Service Selection
    service text,

    -- Step 2: Service-Specific Questions
    -- Life Insurance
    gender text,
    smoker text,
    smoker_details text,
    coverage_amount_life text,
    term_length text,
    pre_existing_conditions text,
    conditions_details_life text,

    -- Visitor Insurance
    coverage_start_date_visitor text,
    coverage_end_date_visitor text,
    coverage_amount_visitor text,
    conditions_details_visitor text,
    purpose_of_visit text,

    -- Supervisa Insurance
    coverage_amount_super_visa text,
    conditions_details_super_visa text,
    coverage_duration_super_visa text,
    relationship_to_applicant text,

    -- RESP
    resp_contribution_goal text,
    resp_investment_horizon text,
    resp_has_savings text,
    resp_savings_amount text,

    -- TFSA
    tfsa_annual_contribution text,
    tfsa_investment_style text,
    tfsa_has_existing text,
    tfsa_existing_amount text,
    tfsa_start_contribution text,

    -- RRSP
    rrsp_retirement_age text,
    rrsp_annual_contribution text,
    rrsp_investment_style text,
    rrsp_has_existing text,
    rrsp_existing_balance text,
    rrsp_start_advice text,

    -- Extended Health and Dental Plan
    health_has_existing_plan text,
    health_existing_coverage_details text,
    health_coverage_need text,
    health_who_needs_coverage text,

    -- Travel Insurance for Canadians
    travel_destination text,
    travel_start_date text,
    travel_end_date text,
    travel_coverage_amount text,
    travel_pre_existing_conditions text,
    travel_conditions_details text,

    -- International Students Plan
    international_school_name text,
    international_coverage_start_date text,
    international_coverage_end_date text,
    international_coverage_amount text,
    international_pre_existing_conditions text,
    international_conditions_details text,

    -- Step 3: Contact Information
    full_name text,
    dob text,
    email text,
    phone text,
    city_province text
);

-- Sequence and Primary Key
ALTER TABLE public.quote_submissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quote_submissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.quote_submissions
    ADD CONSTRAINT quote_submissions_pkey PRIMARY KEY (id);

-- Row-Level Security
ALTER TABLE public.quote_submissions OWNER TO postgres;
GRANT ALL ON TABLE public.quote_submissions TO anon;
GRANT ALL ON TABLE public.quote_submissions TO authenticated;
GRANT ALL ON TABLE public.quote_submissions TO postgres;
GRANT ALL ON TABLE public.quote_submissions TO service_role;

ALTER TABLE public.quote_submissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.quote_submissions FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON public.quote_submissions FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable all for service role" ON public.quote_submissions TO service_role USING (true) WITH CHECK (true);
